import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import attachmentsRouter from "./attachments";
import settingsRouter from "./settings";
import usersRouter from "./users";
import classificationsRouter from "./classifications";
import dossiersRouter from "./dossiers";
import documentsRouter from "./documents";
import protocolsRouter from "./protocols";
import tasksRouter from "./tasks";
import workflowsRouter from "./workflows";
import dossierWorkflowsRouter from "./dossierWorkflows";
import signaturesRouter from "./signatures";
import dashboardRouter from "./dashboard";
import searchRouter from "./search";
import driveRouter from "./drive";
import auditRouter from "./audit";
import importRouter from "./import";
import integrityRouter from "./integrity";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(attachmentsRouter);
router.use(settingsRouter);
router.use(dashboardRouter);
router.use(usersRouter);
router.use(classificationsRouter);
router.use(dossiersRouter);
router.use(documentsRouter);
router.use(protocolsRouter);
router.use(tasksRouter);
router.use(workflowsRouter);
router.use(dossierWorkflowsRouter);
router.use(signaturesRouter);
router.use(searchRouter);
router.use(driveRouter);
router.use(auditRouter);
router.use(importRouter);
router.use(integrityRouter);

export default router;
